name: projet_prog_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700

  uses-material-design: true


